### ISSUE TITLE
package ‘psiplot’ is not available (for R version 3.3.0) 

### ISSUE THREAD

**Issue by aghr** [kcha/psiplot#6]
On a recent R 3.3.0 trying to install psiplot is not possible with standard routine:

library(devtools)
library(roxygen2)
install.packages("psiplot", dependencies=TRUE, repos='http://cran.us.r-project.org', lib="/xxx/yyy/zzz")

Warning message:
package ‘psiplot’ is not available (for R version 3.3.0)

**Comment by kcha** [comment]
Please use `devtools::install_github()` to install psiplot. You may also need to update devtools if you recently upgraded to R 3.3.0.
